[package]
name = "klimowww"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "~1"
futures-lite = "~1"
lazy_static = "~1"
regex = "~1"
tokio = { version = "~1", features = ["macros", "rt-multi-thread"] }
